name: quizzybea_in
description: "QuizzyBea â€“ A modern, engaging quiz app for champions."

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  liquid_pull_to_refresh: ^3.0.1

  # State management & routing
  provider: ^6.1.2
  go_router: ^14.6.1

  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.1

  # Image upload
  http: ^1.2.2
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/images/
    - Assets/lottie/
    - Assets/productimages/

flutter_native_splash:
  color: "#0B0C19"
  image: Assets/images/Quizzybeein.png
  android_12:
    color: "#0B0C19"
    image: Assets/images/Quizzybeein.png
